### ISSUE TITLE
Go through the site content to make sure it's all accurate

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-procurement-explorer#2]
I used the flowchart below to generate the site. @hamhands @shellicious if one of you have some time tomorrow or Sunday, could you poke through the content really quick to make sure I didn't totally bust anything? Feel free to comment on this issue and/or open a PR with fixes.

![city purchasing flowchart](https://cloud.githubusercontent.com/assets/1957344/6091043/a50d53c8-ae65-11e4-9868-480d516f9de0.png)

**Comment by bsmithgall** [comment]
As @hamhands pointed out, this should also include a rewrite of the `index.html` page to include better up-front that prompts what it is what is actually going on here.

**Comment by msknee** [comment]
To piggyback on @hamhands' comment, Gov.UK does a good job of explaining the context for their step-by-step "quiz" UX. Here's an example: https://www.gov.uk/calculate-state-pension

**Comment by bsmithgall** [comment]
This should be pretty straightforward to fix as long as we have some copy for it.

**Comment by bsmithgall** [comment]
Fixed by #4
