### ISSUE TITLE
Change styles to make this in line with Wexplorer

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-procurement-explorer#6]
The current site:

![screen shot 2015-02-10 at 7 17 17 am](https://cloud.githubusercontent.com/assets/1957344/6127081/f37235c4-b0f4-11e4-863a-3315e35aacd5.png)

Currently on Wexplorer:

![screen shot 2015-02-10 at 7 17 33 am](https://cloud.githubusercontent.com/assets/1957344/6127083/f8292f32-b0f4-11e4-994e-aa796911a549.png)

Unification would be pretty simple at this point:
- Change the color schemes
- Change the fonts
- Maybe merge the button styles? (Though I sort of prefer the Pure buttons)

**Comment by hamhands** [comment]
Footer needs work 
![screen shot 2015-02-10 at 9 25 10 am](https://cloud.githubusercontent.com/assets/3640800/6128811/392cf57e-b107-11e4-8254-e879e138d3a5.png)
![screen shot 2015-02-10 at 9 25 04 am](https://cloud.githubusercontent.com/assets/3640800/6128810/392a7cc2-b107-11e4-92d4-7f41b7a87f4a.png)

**Comment by bsmithgall** [comment]
More details plz

**Comment by hamhands** [comment]
Footer link color and items not in line with wexplorer. If we want to include a github link we should probably have them on both apps.

**Comment by bsmithgall** [comment]
Ah ok. Should we have a standard footer then? The Wexplorer one would be pretty to replicate.
